/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec, HttpContext} from '@angular/common/http';
import {CustomHttpParameterCodec} from '../encoder';
import {Observable} from 'rxjs';

// @ts-ignore
import {ChangeTravelOfferQueryDto} from '../model/changeTravelOfferQueryDto';
// @ts-ignore
import {PageDtoTravelOffersDetailsDto} from '../model/pageDtoTravelOffersDetailsDto';
// @ts-ignore
import {SearchTravelOffersQueryDto} from '../model/searchTravelOffersQueryDto';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';

@Injectable({
    providedIn: 'root',
})
export class OfferService extends BaseService {
    constructor(
        protected httpClient: HttpClient,
        @Optional() @Inject(BASE_PATH) basePath: string | string[],
        @Optional() configuration?: Configuration,
    ) {
        super(basePath, configuration);
    }

    /**
     * adds a travel offer
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addTravelOffer(
        observe?: 'body',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<PageDtoTravelOffersDetailsDto>;
    public addTravelOffer(
        observe?: 'response',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpResponse<PageDtoTravelOffersDetailsDto>>;
    public addTravelOffer(
        observe?: 'events',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpEvent<PageDtoTravelOffersDetailsDto>>;
    public addTravelOffer(
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['text/plain', 'application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/offer/cmd/add`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<PageDtoTravelOffersDetailsDto>('post', `${basePath}${localVarPath}`, {
            context: localVarHttpContext,
            responseType: <any>responseType_,
            ...(withCredentials ? {withCredentials} : {}),
            headers: localVarHeaders,
            observe: observe,
            transferCache: localVarTransferCache,
            reportProgress: reportProgress,
        });
    }

    /**
     * changes a travel offer
     * @param changeTravelOfferQueryDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changeTravelOffer(
        changeTravelOfferQueryDto: ChangeTravelOfferQueryDto,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<PageDtoTravelOffersDetailsDto>;
    public changeTravelOffer(
        changeTravelOfferQueryDto: ChangeTravelOfferQueryDto,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpResponse<PageDtoTravelOffersDetailsDto>>;
    public changeTravelOffer(
        changeTravelOfferQueryDto: ChangeTravelOfferQueryDto,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpEvent<PageDtoTravelOffersDetailsDto>>;
    public changeTravelOffer(
        changeTravelOfferQueryDto: ChangeTravelOfferQueryDto,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<any> {
        if (changeTravelOfferQueryDto === null || changeTravelOfferQueryDto === undefined) {
            throw new Error('Required parameter changeTravelOfferQueryDto was null or undefined when calling changeTravelOffer.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['text/plain', 'application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = ['application/json'];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/offer/cmd/change`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<PageDtoTravelOffersDetailsDto>('post', `${basePath}${localVarPath}`, {
            context: localVarHttpContext,
            body: changeTravelOfferQueryDto,
            responseType: <any>responseType_,
            ...(withCredentials ? {withCredentials} : {}),
            headers: localVarHeaders,
            observe: observe,
            transferCache: localVarTransferCache,
            reportProgress: reportProgress,
        });
    }

    /**
     * lists all travel offers
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listTravelOffers(
        observe?: 'body',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<PageDtoTravelOffersDetailsDto>;
    public listTravelOffers(
        observe?: 'response',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpResponse<PageDtoTravelOffersDetailsDto>>;
    public listTravelOffers(
        observe?: 'events',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpEvent<PageDtoTravelOffersDetailsDto>>;
    public listTravelOffers(
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<any> {
        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['text/plain', 'application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/offer/cmd/list`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<PageDtoTravelOffersDetailsDto>('post', `${basePath}${localVarPath}`, {
            context: localVarHttpContext,
            responseType: <any>responseType_,
            ...(withCredentials ? {withCredentials} : {}),
            headers: localVarHeaders,
            observe: observe,
            transferCache: localVarTransferCache,
            reportProgress: reportProgress,
        });
    }

    /**
     * searches travel offers
     * @param searchTravelOffersQueryDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchTravelOffers(
        searchTravelOffersQueryDto: SearchTravelOffersQueryDto,
        observe?: 'body',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<PageDtoTravelOffersDetailsDto>;
    public searchTravelOffers(
        searchTravelOffersQueryDto: SearchTravelOffersQueryDto,
        observe?: 'response',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpResponse<PageDtoTravelOffersDetailsDto>>;
    public searchTravelOffers(
        searchTravelOffersQueryDto: SearchTravelOffersQueryDto,
        observe?: 'events',
        reportProgress?: boolean,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<HttpEvent<PageDtoTravelOffersDetailsDto>>;
    public searchTravelOffers(
        searchTravelOffersQueryDto: SearchTravelOffersQueryDto,
        observe: any = 'body',
        reportProgress: boolean = false,
        options?: {httpHeaderAccept?: 'text/plain' | 'application/json'; context?: HttpContext; transferCache?: boolean},
    ): Observable<any> {
        if (searchTravelOffersQueryDto === null || searchTravelOffersQueryDto === undefined) {
            throw new Error('Required parameter searchTravelOffersQueryDto was null or undefined when calling searchTravelOffers.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined =
            options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['text/plain', 'application/json']);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = ['application/json'];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/offer/cmd/search`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<PageDtoTravelOffersDetailsDto>('post', `${basePath}${localVarPath}`, {
            context: localVarHttpContext,
            body: searchTravelOffersQueryDto,
            responseType: <any>responseType_,
            ...(withCredentials ? {withCredentials} : {}),
            headers: localVarHeaders,
            observe: observe,
            transferCache: localVarTransferCache,
            reportProgress: reportProgress,
        });
    }
}
