/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AngebotDetailsDto} from './angebotDetailsDto';

export interface PageDtoAngebotDetailsDto {
    elements: Array<AngebotDetailsDto>;
    totalCount: number;
}
