openapi: '3.0.0'

info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8900/
    description: Generated server url
paths:
  /api/angebot/cmd/list:
    post:
      tags:
        - angebot
      description: Liefert alle Angebote
      operationId: listAngebote
      responses:
        "500":
          description: INTERNAL_SERVER_ERROR
          content:
            text/plain:
              schema:
                type: string
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDtoAngebotDetailsDto'
  /api/angebot/cmd/add:
    post:
      tags:
        - angebot
      description: Fuegt ein Angebot hinzu
      operationId: addAngebot
      responses:
        "500":
          description: INTERNAL_SERVER_ERROR
          content:
            text/plain:
              schema:
                type: string
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDtoAngebotDetailsDto'
  /api/angebot/cmd/change:
    post:
      tags:
        - angebot
      description: Aendert ein Angebot
      operationId: changeAngebot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeAngebotQueryDto"
      responses:
        "500":
          description: INTERNAL_SERVER_ERROR
          content:
            text/plain:
              schema:
                type: string
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDtoAngebotDetailsDto'
  /api/angebot/cmd/search:
    post:
      tags:
        - angebot
      description: Suche nach Angeboten
      operationId: searchAngebot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchAngebotQueryDto"
      responses:
        "500":
          description: INTERNAL_SERVER_ERROR
          content:
            text/plain:
              schema:
                type: string
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageDtoAngebotDetailsDto'
components:
  schemas:
    ChangeAngebotQueryDto:
      type: object
      properties:
        index:
          type: number
    SearchAngebotQueryDto:
      type: object
      properties:
        name:
          type: string
        nights:
          type: number
    PageDtoAngebotDetailsDto:
      type: object
      properties:
        elements:
          type: array
          items:
            $ref: '#/components/schemas/AngebotDetailsDto'
        totalCount:
          type: integer
      required:
        - elements
        - totalCount
    AngebotDetailsDto:
      type: object
      properties:
        id:
          type: number
        header:
          type: string
        content:
          type: array
          items:
            type: string
        from:
          type: string
          format: date-time
          description: Zeitpunkt der letzten Bearbeitung
        to:
          type: string
          format: date-time
          description: Zeitpunkt der letzten Bearbeitung
        price:
          type: number
      required:
        - header
        - content
        - from
        - to
        - price
